[package]
name = "robbb"
version = "0.1.0"
authors = ["elkowar <5300871+elkowar@users.noreply.github.com>"]
edition = "2018"


[dependencies]
serenity = { version = "0.10", features = ["collector"]}
serenity_utils = "0.6"
anyhow = "1.0"
chrono = "0.4"
chrono-humanize = "0.2"
itertools = "0.10"
indoc = "1.0"
lazy_static = "1.4"
rand = "0.8"
humantime = "2"
thiserror = "1.0"
sqlx = { version ="0.5", features = ["runtime-tokio-rustls", "sqlite", "chrono", "offline"] }
serde_json = "1"
serde = "1"
maplit = "1"
byte-unit = "4.0"
url = "2"
regex = "1"
reqwest = { version = "0.11" }
tokio = { version = "1.7", features = ["macros", "fs", "rt-multi-thread"]}
tokio-util = { version = "0.6", features = ["compat"] }

log = "0.4"
pretty_env_logger = "0.4"
