[package]
name = "robbb"
version = "0.1.0"
authors = ["elkowar <5300871+elkowar@users.noreply.github.com>"]
edition = "2018"


[dependencies]
#serenity = { git = "https://github.com/serenity-rs/serenity/", branch = "next", features = ["collector"]}
serenity = { version = "0.10.10", features = ["collector"]}
anyhow = "1.0"
chrono = "0.4"
chrono-humanize = "0.2"
itertools = "0.10"
indoc = "1.0"
lazy_static = "1.4"
rand = "0.8"
humantime = "2"
thiserror = "1.0"
sqlx = { version ="0.5", features = ["runtime-tokio-rustls", "sqlite", "chrono", "offline"] }
serde_json = "1"
serde = "1"
maplit = "1"
byte-unit = "4.0"
url = "2"
regex = "1"
reqwest = { version = "0.11" }
tokio = { version = "1.15", features = ["macros", "fs", "rt-multi-thread"]}
tokio-util = { version = "0.6", features = ["compat"] }
futures = "0.3"

unicase = "2.6.0"

tracing = "0.1.29"
tracing-log = "0.1.2"
tracing-futures = "0.2.5"
tracing-subscriber = "0.2.25"
tracing-honeycomb = "0.4.2"
libhoney-rust = "0.1.6"
cpu-monitor = "0.1.1"

