on: [push, pull_request]

name: clippy

jobs:
  clippy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add clippy
      - run: cargo clippy -- -D warnings

