name: Docker

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: robbb

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v10
        with:
          name: robbb
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build image
        run: |
          docker load < $(nix-build -E '(import <nixpkgs> {}).callPackage ./. { robbbSrc = builtins.fetchGit ./.; robbbRev = "${{ github.sha }}"; }' -A image)

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:${{ github.sha }}

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          echo IMAGE_ID=$IMAGE_ID

          docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_ID
          docker push $IMAGE_ID
